set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",*:RGB"

set -g mouse on
set -g set-clipboard on

set -g history-limit 50000

set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on

unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

bind -n M-1 select-window -t 1
bind -n M-2 select-window -t 2
bind -n M-3 select-window -t 3
bind -n M-4 select-window -t 4
bind -n M-5 select-window -t 5
bind -n M-6 select-window -t 6
bind -n M-7 select-window -t 7
bind -n M-8 select-window -t 8
bind -n M-9 select-window -t 9
bind -n M-0 select-window -t 10
bind -n M-t new-window

bind h split-window -h -c "#{pane_current_path}"
bind v split-window -v -c "#{pane_current_path}"

bind r source-file ~/.tmux.conf \;

bind -T root F12 \
  set prefix None \;\
  set key-table off \;\
  set mouse off \;\
  set status off \;\
  if -F '#{pane_in_mode}' 'send-keys -X cancel' \;\
  refresh-client -S

bind -T off F12 \
  set -u prefix \;\
  set -u key-table \;\
  set -u mouse \;\
  set status on \;\
  refresh-client -S

set -g status-interval 60
set -g visual-activity off
set -g visual-bell off
set -g visual-silence off
setw -g monitor-activity off
set -g bell-action none
set -g pane-border-style 'fg=white'
set -g pane-active-border-style 'fg=white'
set -g status-position bottom
set -g status-justify left
set -g status-style 'fg=white'
set -g status-left ''
set -g status-right '#[fg=blue,bg=#1e1e2e]#[fg=black,bg=blue] %m/%d/%Y %H:%M '
set -g status-right-style 'fg=black bg=blue'
setw -g window-status-current-style 'fg=black bg=green'
setw -g window-status-current-format ' #I #W #[fg=green,bg=#1e1e2e]#[default]'
setw -g window-status-style 'fg=black bg=blue'
setw -g window-status-format ' #I #W #[fg=blue,bg=#1e1e2e]#[default]'
set -g message-style 'fg=black bg=green'
