set -g default-terminal 'tmux-256color'
set -ag terminal-overrides ',*:RGB'

set -g @catppuccin_flavor 'mocha'
set -g @catppuccin_window_status_style 'rounded'
set -g @catppuccin_status_background '#{@thm_bg}'
set -g @catppuccin_window_text ' #W#{?window_zoomed_flag, (+),}'
set -g @catppuccin_window_current_text ' #W#{?window_zoomed_flag, (+),}'
set -g @catppuccin_date_time_text ' %a %b %d %H:%M'

if 'test ! -f ~/.config/tmux/plugins/catppuccin/catppuccin.tmux' \
  'run "mkdir -p ~/.config/tmux/plugins/catppuccin && git clone -b v2.3.0 https://github.com/catppuccin/tmux.git ~/.config/tmux/plugins/catppuccin"'
run ~/.config/tmux/plugins/catppuccin/catppuccin.tmux

set -g status-interval 60
set -g status-left-length 100
set -g status-left ''
set -g status-right-length 100
set -g status-right '#{E:@catppuccin_status_session}'
set -ag status-right '#{E:@catppuccin_status_date_time}'
set -g message-style 'fg=#{@thm_green},bg=#{@thm_bg},fill=#{@thm_bg},align=left'

set -g mouse on
set -g set-clipboard on
set -g focus-events on

set -g history-limit 50000

set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on

set-hook -g session-created 'run-shell "tmux move-window -r -t #{session_name}"'

unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

# Smart pane switching with awareness of Vim splits.
# See: https://github.com/christoomey/vim-tmux-navigator#disable-wrapping
vim_pattern='(\S+/)?g?\.?(view|l?n?vim?x?|fzf)(diff)?(-wrapped)?'
is_vim="ps -o state= -o comm= -t '#{pane_tty}' | grep -iqE '^[^TXZ ]+ +${vim_pattern}$'"
bind -n 'M-H' if "$is_vim" { send-keys M-H } { if -F '#{pane_at_left}'   {} { select-pane -L } }
bind -n 'M-J' if "$is_vim" { send-keys M-J } { if -F '#{pane_at_bottom}' {} { select-pane -D } }
bind -n 'M-K' if "$is_vim" { send-keys M-K } { if -F '#{pane_at_top}'    {} { select-pane -U } }
bind -n 'M-L' if "$is_vim" { send-keys M-L } { if -F '#{pane_at_right}'  {} { select-pane -R } }
bind -T copy-mode-vi 'M-H' if -F '#{pane_at_left}'   {} { select-pane -L }
bind -T copy-mode-vi 'M-J' if -F '#{pane_at_bottom}' {} { select-pane -D }
bind -T copy-mode-vi 'M-K' if -F '#{pane_at_top}'    {} { select-pane -U }
bind -T copy-mode-vi 'M-L' if -F '#{pane_at_right}'  {} { select-pane -R }

bind -n M-1 select-window -t 1
bind -n M-2 select-window -t 2
bind -n M-3 select-window -t 3
bind -n M-4 select-window -t 4
bind -n M-5 select-window -t 5
bind -n M-6 select-window -t 6
bind -n M-7 select-window -t 7
bind -n M-8 select-window -t 8
bind -n M-9 select-window -t 9
bind -n M-0 select-window -t 10
bind -n M-t new-window -c "#{pane_current_path}"

bind s split-window -v -c '#{pane_current_path}'
bind v split-window -h -c '#{pane_current_path}'

bind N command-prompt -p "New session name:" { if -F "#{==:%1,}" { new-session } { new-session -s "%1" } }
bind X switch-client -n \; run-shell "tmux kill-session -t '#{session_name}'"

bind r source-file ~/.config/tmux/tmux.conf \; display 'config reloaded'

set-window-option -g mode-keys vi

bind -n 'C-x' if "$is_vim" { send-keys C-x } { copy-mode }
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi V send-keys -X rectangle-toggle
bind -T copy-mode-vi y send-keys -X copy-selection-and-cancel
bind -T copy-mode-vi MouseDown1Pane select-pane \; send-keys -X clear-selection
bind -T copy-mode-vi i send-keys -X cancel

bind -T root F12 \
  set prefix None \;\
  set key-table off \;\
  set mouse off \;\
  set status off \;\
  if -F '#{pane_in_mode}' 'send-keys -X cancel' \;\
  refresh-client -S

bind -T off F12 \
  set -u prefix \;\
  set -u key-table \;\
  set -u mouse \;\
  set status on \;\
  refresh-client -S
